name: Generate APK
on:
  push:
    branches: [ main ]
    
jobs:
  # Run Unit Tests etc before Generating APK here.
  # ....
    
  # A job to generate debug APK and upload on Github Artifacts
  apk:
      name: Generate APK
      runs-on: ubuntu-18.04

      steps:
        - uses: actions/checkout@v1
        - name: set up JDK
          uses: actions/setup-java@v1
          with:
            java-version: 11.0.3

        - name: Grant Permission to Execute
          run: chmod +x gradlew

        - name: Build debug APK
          run: bash ./gradlew assembleDebug --stacktrace

        - name: Upload APK to Github Artifacts
          uses: actions/upload-artifact@v3.0.0
          with:
            name: apk.zip
            path: app/build/outputs/apk/debug/app-debug.apk
         
        - name: extract-7z-action
          # You may pin to the exact commit or the version.
          # uses: DuckSoft/extract-7z-action@6eaaa506b410f047eaa9b22498696aad1e19a834
          uses: DuckSoft/extract-7z-action@v1.0
          with:
            # archive path to extract
            pathSource: apk.zip
            # path to place the extract
            pathTarget: app
